[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
port = 8501
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
